using System.Collections.Generic;

namespace SevenBoldPencil.OpenWorld;

public static class Scenes
{
	public static HashSet<string> Factory = new()
	{
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Day_Scripts.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Day_Light.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Areas.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Main_Building.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Basement.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Admin_Office.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Laboratory.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Background.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_DesignStuff.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_DesignMain.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_AI.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Sound_Rework.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Quests.unity",
		// "Assets/Content/Locations/Factory_Rework/Factory_Rework_Day_Culling.unity",
	};

	public static HashSet<string> Customs = new()
	{
		// "Assets/Content/Locations/Custom/custom_Scripts.unity",
		"Assets/Content/Locations/Custom/custom_Terrain.unity",
		"Assets/Content/Locations/Custom/custom_mazuto.unity",
		"Assets/Content/Locations/Custom/custom_Garage.unity",
		"Assets/Content/Locations/Custom/custom_Tamozhnya.unity",
		"Assets/Content/Locations/Custom/custom_TrailerPark.unity",
		"Assets/Content/Locations/Custom/custom_factoryStorageZone.unity",
		"Assets/Content/Locations/Custom/custom_Obshezhitie.unity",
		"Assets/Content/Locations/Custom/custom_Obshezhitie_1_indoor.unity",
		"Assets/Content/Locations/Custom/custom_Obshezhitie_2_indoor.unity",
		"Assets/Content/Locations/Custom/custom_AZS.unity",
		"Assets/Content/Locations/Custom/custom_city.unity",
		"Assets/Content/Locations/Custom/custom_multiScene.unity",
		"Assets/Content/Locations/Custom/custom_Road.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/custom_Abandoned_Lab.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/custom_Abandoned_Plant.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/Custom_ChemicalFactory.unity",
		"Assets/Content/Locations/Custom/custom_AZS_old.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/Custom_Construction_Factory.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/custom_Pump_Station.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/Custom_RepairBox.unity",
		"Assets/Content/Locations/Custom/Custom_Expansion_Temp/Custom_Expansion.unity",
		"Assets/Content/Locations/Custom/custom_background.unity",
		// "Assets/Content/Locations/Custom/custom_Light.unity",
		// "Assets/Content/Locations/Custom/custom_DesignStuff.unity",
		// "Assets/Content/Locations/Custom/custom_DesignMain.unity",
		// "Assets/Content/Locations/Custom/custom_AI.unity",
		// "Assets/Content/Locations/Custom/Custom_Sound.unity",
		// "Assets/Content/Locations/Custom/custom_Culling.unity",
	};

	public static HashSet<string> Reserve = new()
	{
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_Scripts.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Terrain.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_VOHR_Camps.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_TrainStation.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Storages.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Roads.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_RLS_Block.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Repairing_base.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Platz.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Mortar_Position.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_MilitaryDorms.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Main_Checkpoint.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_HQ.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_BunkersBig.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_transition.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_shaft.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_Corridor_B.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_Corridor_A.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_ClimatControl_room.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_Block_A.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_Block_B.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Academy_and_Kitchens.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Casarms.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Main_RTS.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_PTOR.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_1.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_2.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_3.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_4.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_5.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_6.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_7.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_8.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_9.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_10.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_outside_BLOCK_11.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_Bunkers.unity",
		"Assets/Content/Locations/Reserve_Base/Reserve_Base_RLS_Station.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_Train.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_basement_Exit.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_Background.unity",
		// "Assets/Content/Locations/Reserve_Base/Rezerv_Base_Bunkers2.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_vegetable_warehouse.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_Light.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_DesignStuff.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_DesignMain.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_AI.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Sound.unity",
		// "Assets/Content/Locations/Reserve_Base/Reserve_Base_Culling.unity",
	};

	public static HashSet<string> Lighthouse = new()
	{
		// "Assets/Content/Locations/Lighthouse/Lighthouse_Scripts.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Terrain.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Abadonned_pier.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Fisher_Village.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Bus_Stop.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Chalet.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Background.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Complex.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Roads.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Main.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Marina.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Small_RLS_base.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_SummerHotel.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_SwampVillage.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Tower.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_TrainStation.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Logistics_Terminal.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Tunnel.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Water_filter_facility_01.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Water_filter_facility_02.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_Water_filter_facility_03.unity",
		"Assets/Content/Locations/Lighthouse/Lighthouse_WaterStation.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_island.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_Light.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_DesignStuff.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_DesignMain.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_AI.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_Sound.unity",
		// "Assets/Content/Locations/Lighthouse/Lighthouse_Culling.unity",
	};

	public static HashSet<string> Shoreline = new()
	{
		// "Assets/Content/Locations/shorline/shoreline_scripts.unity",
		"Assets/Content/Locations/shorline/shoreline_Terrain.unity",
		"Assets/Content/Locations/shorline/Shoreline_North.unity",
		"Assets/Content/Locations/shorline/Shoreline_East.unity",
		"Assets/Content/Locations/shorline/Shoreline_South.unity",
		"Assets/Content/Locations/shorline/Shoreline_West.unity",
		"Assets/Content/Locations/shorline/Shoreline_Middle.unity",
		"Assets/Content/Locations/shorline/shoreline_sanatorium.unity",
		"Assets/Content/Locations/shorline/Shoreline_Sanatorium_indoor.unity",
		"Assets/Content/Locations/shorline/shoreline_parking_sanatorium.unity",
		"Assets/Content/Locations/shorline/shoreline_pirs02.unity",
		"Assets/Content/Locations/shorline/shoreline_azs.unity",
		"Assets/Content/Locations/shorline/shoreline_tunel.unity",
		"Assets/Content/Locations/shorline/shoreline_meteostation.unity",
		// "Assets/Content/Locations/shorline/Shoreline_Light.unity",
		// "Assets/Content/Locations/shorline/Shoreline_DesignMain.unity",
		// "Assets/Content/Locations/shorline/shoreline_DesignStuff.unity",
		// "Assets/Content/Locations/shorline/shoreline_AI.unity",
		// "Assets/Content/Locations/shorline/Shoreline_Sound.unity",
		// "Assets/Content/Locations/shorline/Shoreline_Culling.unity",
	};

	public static HashSet<string> Interchange = new()
	{
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Scripts.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Terrain.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_2.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_indoor.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_outdoor.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_IDEA.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Shops.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_parking_work.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_OLI.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_GOSHAN.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Shops_Floor2.unity",
		"Assets/Content/Locations/Shopping_Mall/Shopping_Mall_indoor_buildup.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_light.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_DesignStuff.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_DesignMain.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_AI.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Sound.unity",
		// "Assets/Content/Locations/Shopping_Mall/Shopping_Mall_Culling.unity",
	};

	public static HashSet<string> Woods = new()
	{
		// "Assets/Content/Locations/Woods/woods_Scripts.unity",
		"Assets/Content/Locations/Woods/woods_terrain.unity",
		"Assets/Content/Locations/Woods/woods_combined.unity",
		// "Assets/Content/Locations/Woods/woods_light.unity",
		// "Assets/Content/Locations/Woods/woods_design_stuff.unity",
		// "Assets/Content/Locations/Woods/woods_DesignMain.unity",
		// "Assets/Content/Locations/Woods/woods_AI.unity",
		// "Assets/Content/Locations/Woods/Woods_Sound.unity",
		// "Assets/Content/Locations/Woods/woods_Culling.unity",
	};

	public static HashSet<string> Streets = new()
	{
		// "Assets/Content/Locations/City/City_Scripts.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_courtyard_B.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Klimova_24.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Lenina_74.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Lenina_74_Indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Nikitskaya_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Nikitskaya_1_Indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Pinewood_Hotel.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_01/City_SE_01_Pinewood_Hotel_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_courtyard_B.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Lenina_76.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Lenina_78.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_1_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/CIty_SE_02_Malevicha_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/CIty_SE_02_Malevicha_2_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_3.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_3_Indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_5.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Malevicha_5_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/CIty_SE_02_Nikitskaya_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/CIty_SE_02_Nikitskaya_2_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_6.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_6_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_8.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_8_Indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_10.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_10_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_10a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Nikitskaya_10a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Primorskiy_49.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Primorskiy_49_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Primorskiy_51.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Primorskiy_51_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Verhnyaya_Sadovaya_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Verhnyaya_Sadovaya_3.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_02/City_SE_02_Verhnyaya_Sadovaya_3_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Cinema.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Cinema_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Cinema_Street.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Lenina_80.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Square_Gagarina.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_03/City_SE_03_Verhnyaya_Sadovaya_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Lenina_84.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_2_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_4_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_4a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_4a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhnyaya_Sadovaya_6.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Nizhynaya_Sadovaya_8.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Primorskiy_53.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Primorskiy_53_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Primorskiy_55.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_04/City_SE_04_Primorskiy_57.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_05/City_SE_05_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_05/City_SE_05_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_05/City_SE_05_Lenina_75.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_05/City_SE_05_Nikitskiy_Market.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_06/City_SE_06_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_06/City_SE_06_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_07/City_SE_07_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_SE_07/City_SE_07_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Chekannaya_15.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Chekannaya_15_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Klimova_18.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Klimova_18_Indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Klimova_20.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_44.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_44_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_46.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_46_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_48.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_48_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_50.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_50_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_52.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Primorskiy_52_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_3.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_3_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_3a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_3a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_5.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_A/City_SW_01_A_Zmeiskiy_5_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Chekannaya_13.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Chekannaya_13_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_1a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_1a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_3.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_3_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_5.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_5b.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Kamchatskaya_5b_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_12.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_14.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_14a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_14a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_16.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_16_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_16a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Klimova_16a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_School_30.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_School_30_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_2_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_4a.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_4a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_6.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_6_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_8.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_01_B/City_SW_01_B_Zmeiskiy_8_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Construction.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Construction_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Construction_outdoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_AutoService.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_AutoService_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_AutoService_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_blockpost.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_RemBox.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_LexOs_RemBox_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Primorskiy_56.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Primorskiy_56_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_7.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_7_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_9.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_9_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_9_Parking.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Razvedchikov_Courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Sparja.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Sparja_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_02/City_SW_02_Sparja_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_courtyad_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_courtyad_B.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Kamchatskaya_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Kamchatskaya_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Klimova_2.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Klimova_6.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Klimova_8.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_03/City_SW_03_Klimova_10.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_Primorskiy_58.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_Primorskiy_58_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_Primorskiy_58_str1.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_Primorskiy_58_str1_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_04/City_SW_04_Primorskiy_60.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_A_Kamchatskaya_12.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_A_Kamchatskaya_16.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_A_Razvedchikov_5.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_B_Razvedchikov_4.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_B_Razvedchikov_4_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_B_Razvedchikov_6.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_Building_Back.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_SW_05/City_SW_05_courtyard_B.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_01/City_NW_01_Cardinal.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_01/City_NW_01_Cardinal_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_01/City_NW_01_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_02/City_NW_02_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_02/City_NW_02_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_02/City_NW_02_Tetris.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_02/City_NW_02_Tetris_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_Klimova_1a.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_Klimova_1a_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_Senator.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_Sportmarket_Lermontova.unity",
		"Assets/Content/Locations/City/City_Areas/City_NW_03/City_NW_03_Sportmarket_Lermontova_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_01/City_NE_01_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_01/City_NE_01_courtyard_A.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_buildings_back.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Primorskiy_43.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Primorskiy_45.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Primorskiy_45_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova_Beluga_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova_courtyard.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova_Foodcourt_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_TD_Klimova_Toy_Store_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Transtechexport.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Transtechexport_indoor.unity",
		"Assets/Content/Locations/City/City_Areas/City_NE_02/City_NE_02_Tyaglovoy_Per_1.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Chekannaya.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Kamchatskaya.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Klimova.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Lenina.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Malevicha.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Nikitskaya.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Primorskiy.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Razvedchikov.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Rohlina.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Sadovaya.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Sahalinskaya.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Tunnel.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Tyaglovoy_Per.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Underground.unity",
		"Assets/Content/Locations/City/City_Areas/City_Roads/City_Roads_Zmeiskiy.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Grass.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_Portals.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_Stencil.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_NE_02_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_NW_01_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_NW_02_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_NW_03_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_Roads_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_01_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_02_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_03_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_04_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_05_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SE_06_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SW_01_A_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SW_01_B_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SW_02_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SW_04_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_Light/City_SW_05_Light.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_NE_02_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_NW_01_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_NW_03_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_Roads_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SE_01_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SE_02_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SE_03_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SE_04_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SW_01_A_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SW_02_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SW_04_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Areas/City_DesignStuff/City_SW_05_DesignStuff.unity",
		// "Assets/Content/Locations/City/City_Design_Main.unity",
		// "Assets/Content/Locations/City/City_Quests.unity",
		// "Assets/Content/Locations/City/City_LevelBorders.unity",
		// "Assets/Content/Locations/City/City_AI.unity",
		// "Assets/Content/Locations/City/City_Sound.unity",
		// "Assets/Content/Locations/City/City_culling.unity",
	};

	public static HashSet<string> GroundZero = new()
	{
		// "Assets/Content/Locations/Sandbox/Sandbox_Scripts.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_bottom_area.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_roads.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_01.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_01_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_01_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_02.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_02_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_02_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_03.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_03_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_03_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_04.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_04_courtyrad.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_04_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_05.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_05_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_05_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_07.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_07_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_07_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_08.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_08_courtyard.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_Area_08_indoor.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_background_01.unity",
		"Assets/Content/Locations/Sandbox/Sandbox_Areas/Sandbox_background_02.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Grass.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Portals.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Stencil.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_01_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_02_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_03_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_04_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_05_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_07_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_Area_08_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_bottom_area_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_background_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Light/Sandbox_roads_Light.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Design_Stuff.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Design_Main.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Quests.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_AI_high.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_LevelBorders.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_Sound.unity",
		// "Assets/Content/Locations/Sandbox/Sandbox_culling.unity",
	};
}
